<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Reports_icon-people-setting</name>
   <tag></tag>
   <elementGuidId>13475748-b649-4577-9c51-ef4b7b3a46b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-app-bar']/div/header/section[2]/div/section/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-people-setting</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-app-bar&quot;)/div[1]/header[@class=&quot;AppBar__appBar___2FGno&quot;]/section[@class=&quot;AppBar__actions___2pOdv&quot;]/div[@class=&quot;Tooltip__tooltip___17_Ie&quot;]/section[@class=&quot;Action__action___3HYxD js-cucumber-tp_tps&quot;]/a[@class=&quot;Action__link___3rymi&quot;]/i[@class=&quot;icon-people-setting&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-app-bar']/div/header/section[2]/div/section/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
   </webElementXpaths>
</WebElementEntity>
